### ISSUE TITLE
Marvel Ultimate Alliance 3

### ISSUE THREAD

**Issue by Charsles** [eArmada8/gust_stuff#3]
hey there, is it possible for you to update your tool to work with Marvel Ultimate Alliance 3 G1M files? it only exports 1 LOD, i can't export the models using "g1m_to_basic_gltf" and when i repack the model back to g1m, for some reason the textures breaks as you can see here. 

![imagem_2024-09-13_234654260](https://github.com/user-attachments/assets/c2b5d86d-c958-4083-9d00-fac271986d1f)

![imagem_2024-09-13_234703564](https://github.com/user-attachments/assets/8bbff3c7-78ef-4596-96c2-b940d3a5ed0e)

simple file in here
https://www.mediafire.com/file/yf5vzvd98qkgavv/waspmodelg1m.rar/file

**Comment by eArmada8** [comment]
Ok, I've collapsed the LoD so that they can be processed without crashing the scripts, see this [commit](https://github.com/eArmada8/gust_stuff/commit/1970cde91a87beb3d525ea59801686881e2e2159).

Available now in [v1.3.10](https://github.com/eArmada8/gust_stuff/releases/tag/v1.3.10).  Let me know if you have any issues, although I may not be able to help (this tool is meant for Atelier games).

**Comment by Charsles** [comment]
THANK YOU SO MUCH!!!! everything is working now.

![Uploading image.png…]()
